### ISSUE TITLE
Errors logged after using the BREAK menu

### ISSUE THREAD

**Issue by edwardsmit** [plausible/ecto_ch#134] opened 2023-10-27 14:14 UTC
I get multiple errors like
`16:08:49.975 [error] Ch.Connection (#PID<0.217.0>) disconnected: ** (Mint.TransportError) socket closed`

After selecting any action in the beam break menu.

To recreate this start a project that actively uses the `ecto_ch` adapter, press ctrl-c, press `c` to continue, and see multiple error lines.

**Comment by ruslandoga** [comment] 2023-10-27 14:26
I've reproduced it with `Ch` and `Mint` and failed to reproduce it with `gen_tcp`. I'll look into it more tomorrow. Thank you for the report!

**Comment by ruslandoga** [comment] 2023-10-27 14:31
The root cause seem to be somewhere in `gen_tcp`:

```elixir
iex> {:ok, socket} = :gen_tcp.connect({127, 0, 0, 1}, 8123, [:binary, active: false])
{:ok, #Port<0.6>}
iex> :gen_tcp.send(socket, "HTTP/1.1 GET /ping\r\n\r\n")
:ok
iex> :gen_tcp.recv(socket, 0, 10)
{:ok, "HTTP/1.1 501 Not Implemented\r\nConnection: Close\r\n\r\n"}
iex>
BREAK: (a)bort (A)bort with dump (c)ontinue (p)roc info (i)nfo
       (l)oaded (v)ersion (k)ill (D)b-tables (d)istribution
c
iex> :gen_tcp.send(socket, "HTTP/1.1 GET /ping\r\n\r\n")
:ok
iex> :gen_tcp.recv(socket, 0, 10)
{:error, :closed}
```

**Comment by ruslandoga** [comment] 2023-10-27 15:02
The root cause seems to be somewhere in `gen_tcp`:

```elixir
iex(25)> {:ok, socket} = :gen_tcp.connect({127, 0, 0, 1}, 8123, [:binary])
{:ok, #Port<0.8>}
iex(26)> flush
:ok
iex(27)> :gen_tcp.send(socket, "GET /ping HTTP/1.1\r\n\r\n")
:ok
iex(28)> flush
{:tcp, #Port<0.8>,
 "HTTP/1.1 200 OK\r\nDate: Fri, 27 Oct 2023 15:00:10 GMT\r\nConnection: Keep-Alive\r\nContent-Type: text/html; charset=UTF-8\r\nTransfer-Encoding: chunked\r\nKeep-Alive: timeout=3\r\nX-ClickHouse-Summary: {\"read_rows\":\"0\",\"read_bytes\":\"0\",\"written_rows\":\"0\",\"written_bytes\":\"0\",\"total_rows_to_read\":\"0\",\"result_rows\":\"0\",\"result_bytes\":\"0\"}\r\n\r\n4\r\nOk.\n\r\n0\r\n\r\n"}
:ok
iex(29)>
BREAK: (a)bort (A)bort with dump (c)ontinue (p)roc info (i)nfo
       (l)oaded (v)ersion (k)ill (D)b-tables (d)istribution
c
iex(29)>
nil
iex(30)> :gen_tcp.send(socket, "GET /ping HTTP/1.1\r\n\r\n")
{:error, :closed}
iex(31)> flush
{:tcp_closed, #Port<0.8>}
```

Not sure what we can do about this 😅

**Comment by ruslandoga** [comment] 2023-11-06 13:04
Closing as this is not something we can fix in `ecto_ch`

**Closed by ruslandoga** 2023-11-06 13:04 UTC
